name: afftok
description: A referral and cashback platform with TikTok-style interface

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  share_plus: ^12.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2     # ✅ تم التحديث
  video_player: ^2.7.0
  http: ^1.6.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/splash.mp4
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
